### ISSUE TITLE
1.2.x crashes with `context.project.removeReflection is not a function`

### ISSUE THREAD

**Issue by keaukraine** [asgerjensen/typedoc-plugin-external-module-map#15]
After updating plugin to `1.2.x` our last docs build crashed with the following error:

```
17:12:41 /var/lib/jenkins/workspace/project/node_modules/typedoc-plugin-external-module-map/plugin.js:107
17:12:41                 context.project.removeReflection(renaming, true);
17:12:41                                 ^
17:12:41 
17:12:41 TypeError: context.project.removeReflection is not a function
17:12:41     at moduleRenames.forEach.item (/var/lib/jenkins/workspace/project/node_modules/typedoc-plugin-external-module-map/plugin.js:107:33)
17:12:41     at Array.forEach (<anonymous>)
17:12:41     at ExternalModuleMapPlugin.onBeginResolve (/var/lib/jenkins/workspace/project/node_modules/typedoc-plugin-external-module-map/plugin.js:83:32)
17:12:41     at triggerEvents (/var/lib/jenkins/workspace/project/node_modules/typedoc/dist/lib/utils/events.js:128:43)
17:12:41     at triggerApi (/var/lib/jenkins/workspace/project/node_modules/typedoc/dist/lib/utils/events.js:110:13)
17:12:41     at eventsApi (/var/lib/jenkins/workspace/project/node_modules/typedoc/dist/lib/utils/events.js:21:18)
17:12:41     at Converter.trigger (/var/lib/jenkins/workspace/project/node_modules/typedoc/dist/lib/utils/events.js:264:13)
17:12:41     at Converter.resolve (/var/lib/jenkins/workspace/project/node_modules/typedoc/dist/lib/converter/converter.js:171:14)
17:12:41     at Converter.convert (/var/lib/jenkins/workspace/project/node_modules/typedoc/dist/lib/converter/converter.js:91:30)
17:12:41     at CliApplication.convert (/var/lib/jenkins/workspace/project/node_modules/typedoc/dist/lib/application.js:61:39)
```

I cannot provide sample TS code to run against because it is not open-sourced.

`1.1.0` works fine.
We use `typedoc` version `0.15.8`.

**Comment by keaukraine** [comment]
Fixed by upgrading `typedoc` package.
