### ISSUE TITLE
TypeError: Class constructor ConverterComponent cannot be invoked without 'new'

### ISSUE THREAD

**Issue by jduhls** [asgerjensen/typedoc-plugin-external-module-map#5]
Recently upgraded typedoc-related modules.

From package.json
```json
{
    "typedoc": "0.14.2",
    "typedoc-plugin-external-module-map": "0.1.0",
    "typedoc-plugin-markdown": "1.1.26",
    "typescript": "~3.2.2"
}
```
```console
Error: The plugin D:\Projects\my-project\node_modules\typedoc-plugin-external-module-map could not be loaded.

TypeError: Class constructor ConverterComponent cannot be invoked without 'new'
    at new ExternalModuleMapPlugin (D:\Projects\my-project\node_modules\typedoc-plugin-external-module-map\plugin.js:43:46)
    at Converter.addComponent (D:\Projects\my-project\node_modules\typedoc\dist\lib\utils\component.js:123:19)
    at Converter.addComponent (D:\Projects\my-project\node_modules\typedoc\dist\lib\converter\converter.js:28:33)
    at module.exports (D:\Projects\my-project\node_modules\typedoc-plugin-external-module-map\index.js:8:17)
    at PluginHost.load (D:\Projects\my-project\node_modules\typedoc\dist\lib\utils\plugins.js:36:21)
    at CliApplication.bootstrap (D:\Projects\my-project\node_modules\typedoc\dist\lib\application.js:42:22)
    at CliApplication.bootstrap (D:\Projects\my-project\node_modules\typedoc\dist\lib\cli.js:24:30)
    at new Application (D:\Projects\my-project\node_modules\typedoc\dist\lib\application.js:31:14)
    at new CliApplication (D:\Projects\my-project\node_modules\typedoc\dist\lib\cli.js:22:1)
    at Object.<anonymous> (D:\Projects\my-project\node_modules\typedoc\bin\typedoc:4:1)

Using TypeScript 3.2.4 from D:\Projects\my-project\node_modules\typescript\lib
```

**Comment by jduhls** [comment]
Looks like:

#https://github.com/TypeStrong/typedoc/issues/943

**Comment by asgerjensen** [comment]
Thanks, lgtm
